FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
RUN dotnet tool install -g dotnet-fsharplint
ENV PATH="/root/.dotnet/tools:${PATH}"	
WORKDIR /App

RUN git clone https://github.com/PathOfBuildingCommunity/PathOfBuilding.git
# Need to add all the lua 'packages' to the root with the rest of the lua in order for require calls to succeed
RUN cp -r ./PathOfBuilding/runtime/lua/* ./PathOfBuilding/src/

# Copy everything
COPY . ./
# Restore as distinct layers
RUN dotnet restore ./PobWrapperDotNet
RUN dotnet restore ./PobWrapperDotNet.Server
# Build and publish a release
RUN dotnet build ./PobWrapperDotNet
RUN dotnet build ./PobWrapperDotNet.Server
RUN dotnet publish -c release -o /App/out --no-restore ./PobWrapperDotNet.Server

FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /App

COPY --from=build-env /App ./
ENV POB_SRC_PATH=/App/PathOfBuilding/src

WORKDIR /App/out
ENTRYPOINT ["dotnet", "./PobWrapperDotNet.Server.dll"]
